const {chromium}=require('playwright'),A=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');
const click=async(a,id)=>page.locator(`[data-act="${a}"]${id?`[data-id="${id}"]`:''}`).first().click();const fill=async(n,v)=>page.locator(`[name="${n}"]`).fill(v);const save=async()=>{await click('preview');if(!await page.locator('[data-act=confirm]').count())throw Error(await page.locator('#modal').innerText());await click('confirm');if(await page.locator('[data-act=confirm]').count())throw Error('Save failed: '+await page.locator('#toast').innerText())};
await click('new-season');await fill('name','Eid 2027');await fill('opening','100000');await fill('partnerName','Partner');await save();
await page.evaluate(()=>{nav('expenses');nav('category','Feeding');nav('settings');nav('backup');goBack()});A.equal(await page.evaluate(()=>route),'settings');await click('back');A.equal(await page.evaluate(()=>route),'category');await click('back');A.equal(await page.evaluate(()=>route),'expenses');await page.evaluate(()=>goBack());A.equal(await page.evaluate(()=>route),'home');
await click('form','goat');await fill('cost','20000');
for(const width of [320,393]){await page.setViewportSize({width,height:852});const tops=await page.locator('[name=paidByMe],[name=partnerPaid]').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().top));A.ok(Math.abs(tops[0]-tops[1])<1,'paired inputs aligned');}
await click('preview');await page.evaluate(()=>goBack());A.equal(await page.locator('[name=cost]').inputValue(),'20000');
await page.screenshot({path:'tmp/app/photo-form.png',fullPage:true});await save();
await click('form','expense');await fill('total','500');await fill('share','500');A.equal(await page.locator('[name=partnerPaid]').getAttribute('required'),null);await fill('partnerPaid','');await save();
await page.evaluate(()=>nav('employees'));await click('form','employee');await fill('name','Worker');await fill('amount','8000');await fill('percent','50');await save();await click('employee');
await click('employee-pay');await fill('amount','2000');await save();A.equal(await page.evaluate(()=>E.employeeSummary(db,detailId).balance),-200000);
await click('employee-in');await click('salary-employee');await save();await click('employee-pay');await fill('amount','2000');await save();await click('employee-pay');await fill('amount','4000');await page.locator('[name=payer]').selectOption('partner');await save();
A.equal(await page.evaluate(()=>E.employeeSummary(db,detailId).balance),0);A.equal(await page.evaluate(()=>E.summary(db,db.current).out),2450000);A.equal(await page.evaluate(()=>E.summary(db,db.current).partner),0);await page.screenshot({path:'tmp/app/employee.png',fullPage:true});
await click('employee-view','me');A.equal(await page.locator('.card .row').count(),2);await click('employee-view','partner');A.equal(await page.locator('.card .row').count(),1);await click('employee-view','total');
await click('employee-more');await click('salary-settings');await page.locator('[name=auto]').check();await fill('day','31');await fill('from','2027-01-01');await click('salary-settings-save');A.equal(await page.evaluate(()=>db.employees[0].autoSalary),true);
await page.evaluate(()=>nav('home'));await click('form','sale');await fill('price','30000');await fill('received','10000');await fill('customer','Test customer');await fill('phone','03000000000');await save();await click('form','receipt');await fill('amount','20000');await save();
await page.evaluate(()=>nav('cash'));await click('sort');await click('sort-set','oldest');A.equal(await page.evaluate(()=>cashFilter.sort),'oldest');await click('sort');await click('sort-set','newest');await page.screenshot({path:'tmp/app/cash.png',fullPage:true});
await page.evaluate(()=>nav('expenses'));await click('expense-cat','Medicine');await click('category-add','Medicine');await fill('total','100');await fill('share','100');await save();A.equal(await page.locator('.hero-value').innerText(),'Rs 100');
await page.evaluate(()=>{window.print=()=>{};printPage('cash')});A.equal(await page.locator('#printDocument table tbody tr').count(),7);await page.evaluate(()=>printPage('customers'));A.equal(await page.locator('#printDocument .print-customer').count(),1);await page.evaluate(()=>printPage('reports'));A.match(await page.locator('#printDocument').innerText(),/Feeding[\s\S]*Medicine[\s\S]*Salary/);await page.emulateMedia({media:'print'});await page.pdf({path:'tmp/app/report.pdf',format:'A4'});await page.emulateMedia({media:'screen'});
for(const r of ['home','expenses','goats','reports','customers','employees','backup','settings']){await page.evaluate(r=>nav(r),r);if(await page.locator('body').evaluate(e=>e.scrollWidth>innerWidth))throw Error('Overflow '+r);if(['home','backup','reports'].includes(r))await page.screenshot({path:`tmp/app/${r}.png`,fullPage:true});}
const saved=await page.evaluate(()=>backupEnvelope());await page.evaluate(()=>nav('home'));await click('seasons');await click('new-season');await fill('name','Solo season');await save();A.equal(await page.locator('[data-id=partner]').count(),0);await click('form','goat');await fill('cost','5000');A.equal(await page.locator('[name=partnerPaid]').count(),0);await save();await click('form','expense');await fill('total','100');A.equal(await page.locator('[name=share]').count(),0);await save();await page.evaluate(()=>nav('employees'));await click('form','employee');await fill('name','Solo worker');await fill('amount','9000');A.equal(await page.locator('[name=percent]').count(),0);await save();await click('employee');A.equal(await page.locator('[data-act=employee-view][data-id=partner]').count(),0);
await page.evaluate(()=>nav('home'));await click('seasons');const soloId=await page.evaluate(()=>db.current);await click('season-edit',soloId);await fill('name','Solo edited');await save();A.equal(await page.evaluate(()=>current().name),'Solo edited');await click('seasons');await click('season-delete',soloId);await click('confirm-action');A.equal(await page.evaluate(()=>db.seasons.length),1);
await page.evaluate(s=>restorePreview(s),saved);await click('restore-confirm');await page.reload();A.equal(await page.evaluate(()=>db.version),2);
// Goat cascade removes sale + receipts and restores owner totals, leaving unrelated expenses.
await page.evaluate(()=>{detailId=db.goats[0].id;nav('goat')});await click('delete');await click('confirm-action');A.equal(await page.evaluate(()=>db.sales.length+db.receipts.length+db.goats.length),0);
// Long press selection, bulk deletion and both payment/expense cascade.
await page.evaluate(()=>nav('employees'));const target=page.locator('[data-employee-id]').first();const box=await target.boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.waitForTimeout(750);await page.mouse.up();await page.mouse.click(5,5);A.equal(await page.locator('[data-select-employee]:checked').count(),1);await click('employees-delete');await click('confirm-action');A.equal(await page.evaluate(()=>db.employees.length+db.employeePayments.length),0);
await page.evaluate(()=>openForm('goat'));await fill('cost','12000');await page.evaluate(()=>{const c=document.createElement('canvas');c.width=20;c.height=20;setPhoto('photo',c.toDataURL('image/jpeg'))});await save();await page.reload();A.equal(await page.evaluate(()=>db.goats.some(g=>g.photo)),true);
// Real v1 startup migration with salary paid by partner.
await page.evaluate(()=>{const old=E.newDB();old.version=1;delete old.employeePayments;delete old.sequence;old.current='old';old.seasons=[{id:'old',name:'Old preserved',start:'2026-01-01',opening:1000000}];old.employees=[{id:'w',season:'old',name:'Old worker',amount:800000,percent:50}];old.expenses=[{id:'e',season:'old',date:'2026-01-01',category:'Salary',employee:'w',month:'2026-01',total:800000,share:400000,paidByMe:0}];localStorage.setItem('bakra-hisab-v1',JSON.stringify(old))});await page.reload();A.equal(await page.evaluate(()=>E.summary(db,'old').out),400000);A.equal(await page.evaluate(()=>E.summary(db,'old').partner),-400000);A.equal(await page.evaluate(()=>E.employeeSummary(db,'w').balance),0);A.ok(await page.evaluate(()=>localStorage.getItem('bakra-hisab-pre-v2')));
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: browser UI update flows, offline persistence, v1 startup migration, salary/advance, optional partner, sorting, category totals, PDF content, photo, season edit/delete and bulk deletion.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
