const {chromium}=require('playwright'),A=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']});const p=await b.newPage({viewport:{width:393,height:852}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765');
await p.evaluate(()=>{const d=E.newDB();d.current='s';d.seasons=[{id:'s',name:'Test season',start:'2026-01-01',opening:0,partnerName:'Partner'}];for(let n=1;n<=18;n++)E.upsert(d,'goats',{id:'g'+n,season:'s',tag:'B-'+String(n).padStart(3,'0'),date:'2026-01-01',cost:100000,paidByMe:100000});E.upsert(d,'employees',{id:'emp',season:'s',name:'Worker',amount:800000,percent:50,autoSalary:true,salaryDay:1,autoFrom:'2026-09-01'});E.addSalary(d,d.employees[0],'2026-09','2026-09-01');E.addSalary(d,d.employees[0],'2026-09','2026-09-01');E.addSalary(d,d.employees[0],'2026-10','2026-10-15');E.validate(d);if(E.accrueSalaries(d,'2026-10-31')!==0)throw Error('Auto salary duplicated');persist(d);render();});
A.equal(await p.evaluate(()=>E.summary(db,'s').expense),1200000);
const click=async(a,id)=>p.locator(`[data-act="${a}"]${id?`[data-id="${id}"]`:''}`).first().click();
await p.evaluate(()=>window.scrollTo(0,320));A.ok(Math.abs(await p.locator('.season').evaluate(e=>e.getBoundingClientRect().top)-8)<2);await p.screenshot({path:'tmp/app/131-home.png'});
await click('nav','goats');const input=p.locator('[data-search]');await input.evaluate(e=>window.originalInput=e);await input.fill('b002');A.equal(await input.evaluate(e=>e===window.originalInput),true);await click('goat-search');A.equal(await p.locator('[data-act=goat]').count(),1);A.match(await p.locator('[data-act=goat]').innerText(),/B-002/);await input.fill('b00');await input.press('Enter');A.equal(await p.locator('[data-act=goat]').count(),9);await p.evaluate(()=>window.scrollTo(0,350));A.ok(Math.abs(await p.locator('.topbar').evaluate(e=>e.getBoundingClientRect().top))<2);A.equal(await p.locator('.cash-actions button').allTextContents().then(x=>x.join('|')),'Add kro|Sell kro');await p.screenshot({path:'tmp/app/131-goats.png'});
await click('form','sale');await p.locator('[name=saleGoat][value=g2]').check();A.equal(await p.locator('[name=priceMode]').isVisible(),false);A.equal(await p.locator('[name=price]').locator('..').locator('span').textContent(),'Sale price *');await p.locator('[name=saleGoat][value=g3]').check();A.equal(await p.locator('[name=priceMode]').isVisible(),true);await click('close');
await click('health-open');await click('health-add');A.equal(await p.locator('[name=followDate],[name=followTime]').count(),0);await click('close');
await p.evaluate(()=>{window.print=()=>{};detailId='emp';printPage('employee');});A.match(await p.locator('#printDocument').innerText(),/Worker/);A.match(await p.locator('#printDocument').innerText(),/Rs 24,000/);
await p.evaluate(()=>{transact(d=>d.settings.sample=true);});A.notEqual(await p.locator('#toast').textContent(),'Phone par save ho gaya');
for(const route of ['cash','expenses','reports']){await p.evaluate(r=>{nav(r);window.scrollTo(0,200)},route);A.ok(Math.abs(await p.locator('.topbar').evaluate(e=>e.getBoundingClientRect().top))<2,route);}
A.equal(errors.length,0,errors.join('\n'));console.log('PASS 1.3.1: repeated manual salary, owner shares, auto dedupe, PDF statement, stable search input/partial search, single sale labels, optional form cleanup, sticky headers and bottom actions');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
