const {chromium}=require('playwright'),A=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:393,height:852}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765');
await p.evaluate(()=>{const d=E.newDB();d.current='solo';d.seasons=[{id:'solo',name:'Solo',start:'2026-01-01',opening:100000},{id:'shared',name:'Shared',start:'2026-01-01',opening:0,partnerName:'Sathi'}];persist(d);render();});
const click=async(a,id)=>p.locator(`[data-act="${a}"]${id?`[data-id="${id}"]`:''}`).first().click();const fill=async(n,v)=>p.locator(`[name="${n}"]`).fill(v);const save=async()=>{await click('preview');A.equal(await p.locator('[data-act=confirm]').count(),1,await p.locator('#modal').innerText());await click('confirm');A.equal(await p.locator('[data-act=confirm]').count(),0,await p.locator('#toast').innerText());};
await click('form','goat');await fill('tag','B');await fill('batch','3');await fill('cost','3000');await fill('rent','300');await fill('mandi','60');A.equal(await p.locator('[name=rentShare]').count(),0);await save();A.equal(await p.evaluate(()=>db.goats.length),3);A.equal(await p.evaluate(()=>db.expenses.reduce((n,e)=>n+e.share,0)),36000);A.equal(await p.evaluate(()=>E.summary(db,db.current).expense),36000);
const goat=await p.evaluate(()=>db.goats[0].id);await p.evaluate(id=>openForm('goat',id),goat);A.equal(await p.locator('[name=rent]').inputValue(),'100');await fill('rent','150');await save();A.equal(await p.evaluate(()=>db.expenses.length),6);A.equal(await p.evaluate(()=>E.summary(db,db.current).expense),41000);
await p.evaluate(()=>nav('goats'));A.equal(await p.locator('[data-list-key]').first().getAttribute('data-list-key'),await p.evaluate(()=> 'goat:'+db.goats.at(-1).id));await click('list-sort');await click('list-sort-set','oldest');A.equal(await p.locator('[data-list-key]').first().getAttribute('data-list-key'),'goat:'+goat);
const inputBox=await p.locator('[data-search]').boundingBox(),iconBox=await p.locator('.search-submit').boundingBox();A.ok(Math.abs(inputBox.y+inputBox.height/2-iconBox.y-iconBox.height/2)<1);
await p.screenshot({path:'tmp/app/132-goats.png'});
const box=await p.locator('[data-list-key]').first().boundingBox();await p.mouse.move(box.x+80,box.y+20);await p.mouse.down();await p.waitForTimeout(700);await p.mouse.up();await p.evaluate(()=>listSuppress=false);A.equal(await p.locator('.list-check').count(),3);A.equal(await p.evaluate(()=>listSelected.size),1);await click('list-delete');A.match(await p.locator('#modal').innerText(),/Kharchay/);await click('list-delete-confirm');A.equal(await p.evaluate(()=>db.goats.length),2);A.equal(await p.evaluate(()=>db.expenses.length),4);
await click('form','sale');await p.locator('[name=saleGoat]').first().check();await fill('price','2000');await fill('received','2000');await fill('rent','40');await fill('mandi','10');await save();A.equal(await p.evaluate(()=>db.expenses.filter(e=>e.tradeType==='sale').length),2);
await p.evaluate(()=>nav('cash'));await click('list-select');A.ok(await p.locator('.list-check').count()>0);await p.locator('[data-list-key^="sale:"]').click();await click('list-delete');A.match(await p.locator('#modal').innerText(),/poori sales/);await click('list-delete-confirm');A.equal(await p.evaluate(()=>db.sales.length),0);A.equal(await p.evaluate(()=>db.expenses.some(e=>e.tradeType==='sale')),false);
for(const r of ['home','cash','expenses','reports']){await p.evaluate(r=>nav(r),r);A.doesNotMatch(await p.locator('#app').innerText(),/mera hissa|mere hissay|mere kharch|MERA HISSA|MERA STOCK|mere expenses/i);}
await p.evaluate(()=>{window.print=()=>{};printPage('reports')});A.doesNotMatch(await p.locator('#printDocument').innerText(),/mera hissa|mere hissay|mere expenses/i);
await p.evaluate(()=>nav('expenses'));A.match(await p.locator('.hero').innerText(),/Total kharcha/);await click('list-select');await click('list-all');await click('list-delete');await click('list-delete-confirm');A.equal(await p.evaluate(()=>db.expenses.length),0);
await p.evaluate(()=>{transact(d=>d.current='shared');nav('home')});A.match(await p.locator('#app').innerText(),/Mere hissay ka kharcha/);
await click('form','goat');await fill('tag','Shared-1');await fill('cost','1000');await fill('rent','200');await p.locator('.trade-fees details').first().locator('summary').click();await fill('rentShare','100');await fill('rentMe','200');await save();A.equal(await p.evaluate(()=>E.summary(db,'shared').expense),10000);A.equal(await p.evaluate(()=>E.summary(db,'shared').partner),10000);
await p.evaluate(()=>nav('health'));A.equal(await p.locator('#app [data-act=health-settings]').count(),0);await p.evaluate(()=>nav('settings'));A.equal(await p.locator('#app [data-act=health-settings]').count(),1);
await p.evaluate(()=>nav('expenses'));await p.screenshot({path:'tmp/app/132-expenses.png'});A.equal(errors.length,0,errors.join('\n'));console.log('PASS 1.3.2 fees/category linking, batch allocation, edits without duplicates, source/linked deletion, long press & bulk delete, sort, solo/shared labels, totals and settings-only notifications.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
