package com.bakrahisab.app;
import android.app.*;
import android.content.*;
import android.os.Build;
import android.net.Uri;
import org.json.*;
import java.time.*;
import java.util.*;

/** Device-local, persistent reminder queue. One alarm wakes the next due batch. */
public final class HealthReminders {
 private static final String CHANNEL="sehat_reminders", PREFS="health_reminders";
 private static android.content.SharedPreferences prefs(Context c){return c.getSharedPreferences(PREFS,Context.MODE_PRIVATE);}
 private static NotificationManager manager(Context c){return (NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);}
 public static void channel(Context c){NotificationChannel ch=new NotificationChannel(CHANNEL,"Sehat reminders",NotificationManager.IMPORTANCE_DEFAULT);ch.setDescription("Deworming, dawa aur vaccination ke offline reminders");manager(c).createNotificationChannel(ch);}
 private static PendingIntent alarm(Context c){return PendingIntent.getBroadcast(c,1300,new Intent(c,HealthAlarmReceiver.class).setAction("com.bakrahisab.app.HEALTH_ALARM"),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 public static boolean allowed(Context c){return (Build.VERSION.SDK_INT<33||c.checkSelfPermission("android.permission.POST_NOTIFICATIONS")==android.content.pm.PackageManager.PERMISSION_GRANTED)&&manager(c).areNotificationsEnabled()&&manager(c).getNotificationChannel(CHANNEL).getImportance()!=NotificationManager.IMPORTANCE_NONE;}
 public static boolean exact(Context c){return Build.VERSION.SDK_INT<31||((AlarmManager)c.getSystemService(Context.ALARM_SERVICE)).canScheduleExactAlarms();}
 public static String status(Context c){channel(c);JSONObject j=new JSONObject();try{j.put("allowed",allowed(c));j.put("exact",exact(c));j.put("error",prefs(c).getString("error",""));}catch(Exception ignored){}return j.toString();}
 public static synchronized void sync(Context c,String json){try{channel(c);JSONObject next=new JSONObject(json);JSONArray events=next.optJSONArray("events");if(events==null)events=new JSONArray();Set<String> keys=new HashSet<>();for(int i=0;i<events.length();i++)keys.add(events.getJSONObject(i).getString("key"));JSONArray old=new JSONArray(prefs(c).getString("events","[]"));for(int i=0;i<old.length();i++){String key=old.getJSONObject(i).getString("key");if(!next.optBoolean("enabled")||!keys.contains(key))manager(c).cancel(key,key.hashCode());}Set<String> fired=new HashSet<>(prefs(c).getStringSet("fired",new HashSet<>()));fired.retainAll(keys);prefs(c).edit().putString("events",events.toString()).putBoolean("enabled",next.optBoolean("enabled")).putStringSet("fired",fired).putString("error","").commit();schedule(c);}catch(Exception e){prefs(c).edit().putString("error","Reminder save nahi hua. Dobara settings save karein.").apply();}}
 static long when(JSONObject e)throws Exception{return LocalDate.parse(e.getString("date")).atTime(LocalTime.parse(e.getString("time"))).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();}
 private static boolean staleLead(JSONObject e,long now)throws Exception{return e.optBoolean("before")&&when(e)<now-86400000L;}
 public static synchronized void schedule(Context c){try{channel(c);AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);am.cancel(alarm(c));if(!prefs(c).getBoolean("enabled",false)||!allowed(c))return;JSONArray events=new JSONArray(prefs(c).getString("events","[]"));Set<String> fired=prefs(c).getStringSet("fired",new HashSet<>());long earliest=Long.MAX_VALUE,now=System.currentTimeMillis();for(int i=0;i<events.length();i++){JSONObject e=events.getJSONObject(i);if(!fired.contains(e.getString("key"))&&!staleLead(e,now))earliest=Math.min(earliest,when(e));}if(earliest==Long.MAX_VALUE)return;long at=Math.max(now+1500,earliest);if(exact(c))am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,alarm(c));else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,alarm(c));prefs(c).edit().putString("error","").apply();}catch(Exception e){prefs(c).edit().putString("error","Phone reminder timing allow nahi kar raha. Settings check karein.").apply();}}
 public static synchronized void deliver(Context c){try{channel(c);if(!prefs(c).getBoolean("enabled",false)||!allowed(c)){schedule(c);return;}JSONArray events=new JSONArray(prefs(c).getString("events","[]"));Set<String> fired=new HashSet<>(prefs(c).getStringSet("fired",new HashSet<>()));long now=System.currentTimeMillis();for(int i=0;i<events.length();i++){JSONObject e=events.getJSONObject(i);String key=e.getString("key");if(fired.contains(key)||when(e)>now||staleLead(e,now))continue;Intent open=new Intent(c,MainActivity.class).setData(Uri.parse("bakrahisab://sehat/"+e.getString("schedule"))).putExtra("healthSchedule",e.getString("schedule")).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pi=PendingIntent.getActivity(c,key.hashCode(),open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(c,CHANNEL).setSmallIcon(com.bakrahisab.app.R.drawable.notification_health).setColor(android.graphics.Color.rgb(9,99,71)).setContentTitle(e.optString("title","Sehat reminder")).setContentText(e.optString("body")).setStyle(new Notification.BigTextStyle().bigText(e.optString("body"))).setVisibility(Notification.VISIBILITY_PRIVATE).setCategory(Notification.CATEGORY_REMINDER).setContentIntent(pi).setAutoCancel(true).build();manager(c).notify(key,key.hashCode(),n);fired.add(key);}prefs(c).edit().putStringSet("fired",fired).commit();schedule(c);}catch(Exception e){prefs(c).edit().putString("error","Notification nahi dikh saki. Phone permissions check karein.").apply();}}
}
